# ============================================================================
# Principal Component Epigenetic Clock Prediction
# ============================================================================

# This script calculates principal-component-based DNA methylation clocks for
# the fasting cohort. It uses the complete processed beta matrix generated by
# 2_prepare_complete_betas_for_clocks.qmd and the three-timepoint metadata table
# to provide methylation profiles, chronological age, sex, and sample IDs to the
# external PC-Clocks pipeline.
#
# Workflow:
#   - Load `data/betas_complete_processed.RDS` and transpose it to samples x CpGs.
#   - Load `data/meta_3timepoints.csv` and prepare the phenotype table expected
#     by the PC-Clocks scripts: `Sample`, `Age`, and binary `Female`.
#   - Run `calcPCClocks()` to estimate PC clock DNAm ages.
#   - Run `calcPCClocks_Accel()` to calculate age-acceleration outputs.
#
# Output:
#   - data/PCClocks.csv: PC clock predictions and acceleration measures for
#     samples with complete age, sex, and methylation inputs.

# FILE PATHS - Update these at the front for easy modifications
# ============================================================================
clocks_dir <- "~/public/SiyuanLuo/projects/fasting_clinics/PC-Clocks/"
utils_file <- "utils.R"
betas_file <- "./data/betas_complete_processed.RDS"
metadata_file <- "data/meta_3timepoints.csv"
output_file <- "data/PCClocks.csv"

# ============================================================================
# Load Libraries
# ============================================================================
library(dplyr)
library(readxl)
library(tidyr)
# ============================================================================
# Load Custom Functions and PC Clocks Scripts
# ============================================================================
source(utils_file)
source(paste(clocks_dir, "run_calcPCClocks.R", sep = ""))
source(paste(clocks_dir, "run_calcPCClocks_Accel.R", sep = ""))

# ============================================================================
# Load Data
# ============================================================================
betas <- readRDS(betas_file)

# ============================================================================
# Prepare the Data
# ============================================================================
datMeth <- t(betas)

meta <- read.table(metadata_file, header = TRUE, sep = ",")
datPheno <- meta[,c("age","Gender","Sample")] %>% drop_na()
names(datPheno)[names(datPheno) == "age"] <- "Age"
datPheno$Female <- as.numeric(datPheno$Gender == "Female")
datMeth <- datMeth[datPheno$Sample, ]

# ============================================================================
# Calculate the Clocks
# ============================================================================
PCClock_DNAmAge <- calcPCClocks(path_to_PCClocks_directory = clocks_dir, 
                                 datMeth = datMeth, datPheno = datPheno)
PCClock_DNAmAge <- calcPCClocks_Accel(PCClock_DNAmAge)

# ============================================================================
# Save Results
# ============================================================================
write.table(PCClock_DNAmAge, 
            file = output_file, 
            sep = ",", 
            row.names = FALSE, 
            col.names = TRUE, 
            quote = FALSE)
